project/auth.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask import redirect, url_for, render_template, request, Blueprint, flash
from flask_sqlalchemy import SQLAlchemy
from flask_login import (
    UserMixin,
    login_user,
    LoginManager,
    login_required,
    current_user,
    logout_user,
)
from . import db
from .models import User
from .forms import LoginForm, NewUserForm

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        # find user by email
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for("main.index"))
            else:
                flash("Wrong password or user, please try again.")
                return redirect(url_for("auth.login"))
        else:
            flash("Wrong user or password, please try again.")
            return redirect(url_for("auth.login"))

    return render_template("login.html", form=form)


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    # Set form as none if users are to be invited since the project is very very small.
    # nform = None

    nform = NewUserForm()

    if nform.validate_on_submit():
        # If user's email already exists
        if User.query.filter_by(email=nform.email.data).first():
            # Send flash messsage
            flash("You've already signed up with that email, log in instead!")
            # Redirect to /login route.
            return redirect(url_for("auth.login"))

        hash_and_salted_password = generate_password_hash(
            nform.password.data, method="pbkdf2:sha256", salt_length=8
        )
        new_user = User(
            email=nform.email.data,
            name=nform.name.data,
            password=hash_and_salted_password,
        )
        db.session.add(new_user)
        db.session.commit()

        # Logging in right after registering so the user can access the
        # full page

        login_user(new_user)

        return redirect(url_for("main.index"))
    if request.method == "POST":
        # Send flash messsage
        flash("Error, check the submitted data, did you confirm your password?")
    return render_template("signup.html", form=nform)


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))

project/views.py
import os
from flask import Blueprint, redirect, render_template, request, url_for, flash
from flask_login import (
    UserMixin,
    login_user,
    LoginManager,
    login_required,
    current_user,
    logout_user,
)
from datetime import date
from project.forms import NewCafeForm
from .models import Cafe
from . import db

INFO_EMAIL = os.environ.get("INFO_EMAIL")

main = Blueprint("main", __name__)


@main.route("/")
def index():
    cafes = Cafe.query.all()
    return render_template("index.html", all_cafes=cafes)


@main.route("/add-cafe", methods=["GET", "POST"])
@login_required
def new_cafe():
    form = NewCafeForm()
    if form.validate_on_submit():
        n_cafe = Cafe(
            name=form.name.data,
            map_url=form.map_url.data,
            img_url=form.img_url.data,
            location=form.location.data,
            seats=form.seats.data,
            has_toilet=form.has_toilet.data,
            has_wifi=form.has_wifi.data,
            has_sockets=form.has_sockets.data,
            can_take_calls=form.can_take_calls.data,
            coffee_price=form.coffee_price.data,
            author=current_user,
            date=date.today().strftime("%B %d, %Y"),
        )
        db.session.add(n_cafe)
        db.session.commit()
        return redirect(url_for("main.index"))

    return render_template("new_cafe.html", form=form)


@main.route("/my-cafes", methods=["GET", "POST"])
@login_required
def my_cafes():
    cafes = Cafe.query.filter_by(author=current_user.name)
    return render_template("index.html", all_cafes=cafes)


@main.route("/delete/<int:cafe_id>")
@login_required
def delete_cafe(cafe_id):
    cafe_to_delete = Cafe.query.get(cafe_id)
    # if its the author or admin delete
    if (cafe_to_delete.author_id == current_user.id) or (current_user.id == 1):
        db.session.delete(cafe_to_delete)
        db.session.commit()
        return redirect(url_for("main.index"))
    else:
        # Send flash messsage
        flash("You have to be the author of the entry or admin to delete it.")
    return redirect(url_for("main.index"))

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Coffee and wifi - iv</title>
  <link rel='shortcut icon' type='image/x-icon' href="{{url_for('static', filename='favicon.ico')}}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
</head>

<body class="d-flex flex-column min-vh-100">
{% include "navbar.html" %}

  {% block content %}
  {% endblock %}

{% include "footer.html" %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>

</html>

project/templates/cards.html
{% macro cafe_card(cafe,current_user) -%}
<div class="card mb-3 mx-auto" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{cafe.img_url}}" class="img-fluid rounded-start card-img-top" alt="{{cafe.name}}">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{cafe.name}}</h5>
        <p class="card-text">
          <b>Location:</b>{{cafe.location}} (<a href="{{cafe.map_url}}">map</a>)
          <br>
          <b>Seats:</b>{{cafe.seats}}&emsp;
          <b>WiFi:</b>{{"Yes" if cafe.has_wifi else "No"}}
          <br>
          <b>Toilets:</b>{{"Yes" if cafe.has_toilet else "No"}}&emsp;
          <b>Sockets:</b>{{"Yes" if cafe.has_sockets else "No"}}
          <br>
          <b>Can take calls?:</b>{{"Yes" if cafe.can_take_calls else "No"}}
        </p>
        {%if cafe.coffee_price%}
        <p class="card-text"><b>Coffee price:</b>{{cafe.coffee_price}}</p>
        {%endif%}
        {% if  (cafe.author_id == current_user.id) or (current_user.id == 1) %}
        <a class="fs-6 text-secondary" href="{{url_for('main.delete_cafe', cafe_id=cafe.id) }}">Delete this
          cafe ✘</a>
        {%endif%}
      </div>
    </div>
  </div>
</div>
{%- endmacro %}

project/templates/footer.html
<!-- Footer -->
<div class="wrapper flex-grow-1"></div>
<footer class="container-fluid pt-2 pb-2 navbar-fixed-bottom">
  <div class="text-center">
    Copyright © Ivan Bautista <span id="cdate">2021</span>
  </div>
  <div class="text-center">
    Find the code on
    <a href="https://github.com/ivanbaug" class="link-light"> GitHub
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github icon-link"
        viewBox="0 0 16 16">
        <path
          d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
      </svg>
    </a>
  </div>
</footer>

project/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="container">
<h2 class="my-4">Beautiful places</h2>
{% if all_cafes %}
  {% from 'cards.html' import cafe_card as show_cafe %}
  {% for cafe in all_cafes %}
    {{show_cafe(cafe, current_user)}}
  {% endfor %}
{% endif %}
</div>
{% endblock content %}

project/templates/login.html
{% extends "base.html" %}
{% block content %}

<br>


<div class="card mx-auto my-5">
  <div class="card-header text-white text-center card-header-custom">
    <strong>User details</strong>
  </div>
  <div class="card-body ">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <form method="POST" action="/login" class="d-grid gap-3">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.email(class='form-control', placeholder='Your e-mail') }}
      </div>
      <div class="form-group">
        {{ form.password(class='form-control', placeholder='Password') }}
      </div>
      <div class="form-check">
        {{ form.remember(class='form-check-input', placeholder='Remember me') }}
        Remember me
      </div>
      <div class="float-right">
        {{ form.submit(class='btn btn-success') }}
      </div>
    </form>
  </div>
</div>




{% endblock content %}

project/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
        class="bi bi-cup d-inline-block" viewBox="0 0 16 16">
        <path
          d="M1 2a1 1 0 0 1 1-1h11a1 1 0 0 1 1 1v1h.5A1.5 1.5 0 0 1 16 4.5v7a1.5 1.5 0 0 1-1.5 1.5h-.55a2.5 2.5 0 0 1-2.45 2h-8A2.5 2.5 0 0 1 1 12.5V2zm13 10h.5a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.5-.5H14v8zM13 2H2v10.5A1.5 1.5 0 0 0 3.5 14h8a1.5 1.5 0 0 0 1.5-1.5V2z" />
      </svg>
      Coffee'n wifi
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if current_user.is_authenticated %}
        <li class="navbar-text"> Welcome back, {{current_user.name}}.</li>
        {% endif %}
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.my_cafes') }}">My sites</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.new_cafe') }}">Add new site</a>
        </li>
        {% endif %}
        {% if not current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.signup') }}">Signup</a>
        </li>
        {% endif %}
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

project/templates/new_cafe.html
{% extends "base.html" %}
{% block content %}

<br>


<div class="card mx-auto my-5 new-cafe-card">
  <div class="card-header text-white text-center card-header-custom">
    <strong>New Cafe Details</strong>
  </div>
  <div class="card-body ">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <form method="POST" action="/add-cafe" class="d-grid gap-1">
      {{ form.csrf_token }}
      <div class="form-group">
        <label>{{form.name.label}}</label>
        {{ form.name(class='form-control') }}
      </div>
      <div class="form-group">
        <label>{{form.map_url.label}}</label>
        {{ form.map_url(class='form-control') }}
      </div>
      <div class="form-group">
        <label>{{form.img_url.label}}</label>
        {{ form.img_url(class='form-control') }}
      </div>
      <div class="form-group">
        <label>{{form.location.label}}</label>
        {{ form.location(class='form-control') }}
      </div>
      <div class="form-group">
        <label>{{form.seats.label}}</label>
        {{ form.seats(class='form-control') }}
      </div>
      <div class="form-check form-switch">
        {{ form.has_toilet(class='form-check-input',) }}
        <label>{{form.has_toilet.label}}</label>
      </div>
      <div class="form-check form-switch">
        {{ form.has_wifi(class='form-check-input',) }}
        <label>{{form.has_wifi.label}}</label>
      </div>
      <div class="form-check form-switch">
        {{ form.has_sockets(class='form-check-input',) }}
        <label>{{form.has_sockets.label}}</label>
      </div>
      <div class="form-check form-switch">
        {{ form.can_take_calls(class='form-check-input',) }}
        <label>{{form.can_take_calls.label}}</label>
      </div>
      <div class="form-group">
        <label>{{form.coffee_price.label}}</label>
        {{ form.coffee_price(class='form-control') }}
      </div>
      <div class="float-right">
        {{ form.submit(class='btn btn-success') }}
      </div>
    </form>
  </div>
</div>

{% endblock content %}

project/templates/signup.html
{% extends "base.html" %}
{% block content %}
<div class="card mx-auto my-5">
  <div class="card-header text-white text-center card-header-custom">
    <strong>Signup</strong>
  </div>
  <div class="card-body">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-danger" role="alert">
      {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
    </div>
    {% endif %}
    {% endwith %}
    <form method="POST" action="/signup" class="d-grid gap-3">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.name(class='form-control', placeholder='Your Name') }}
      </div>
      <div class="form-group">
        {{ form.email(class='form-control', placeholder='Your e-mail') }}
      </div>
      <div class="form-group">
        {{ form.password(class='form-control', placeholder='Password') }}
      </div>
      <div class="form-group">
        {{ form.confirm(class='form-control', placeholder='Confirm your password') }}
      </div>
      <div class="float-right">
        {{ form.submit(class='btn btn-success') }}
      </div>
    </form>
  </div>
</div>
{% endblock content %}